# docker-compose.yml

services:
  redis:
    image: redis:7-alpine
    container_name: deep_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0
    container_name: deep_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: deep_api
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - local_uploads:/app/uploads
    env_file:
      - .env
    command: >
      sh -c "flask db upgrade && gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker --bind 0.0.0.0:5000 run:app"
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

  worker:
    container_name: deep_worker
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
      - local_uploads:/app/uploads
    env_file:
      - .env
    command: celery -A celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
      - api

volumes:
  mysql_data:
  local_uploads: