"""Alterado Frame para usar coluna JSON para emocoes

Revision ID: eb5914dce651
Revises: 362c7b907afb
Create Date: 2025-10-15 23:57:07.399356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb5914dce651'
down_revision = '362c7b907afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotions', mysql.JSON(), nullable=True))
        batch_op.drop_column('confidence')
        batch_op.drop_column('emotion')

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='videostatus', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='videostatus', native_enum=False),
               type_=mysql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'),
               existing_nullable=False)

    with op.batch_alter_table('frames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotion', mysql.ENUM('HAPPY', 'SAD', 'ANGRY', 'SURPRISED', 'NEUTRAL', 'FEAR', 'DISGUST', 'UNIDENTIFIED'), nullable=False))
        batch_op.add_column(sa.Column('confidence', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('emotions')

    # ### end Alembic commands ###
